baseurl: /
languageCode: en-US
title: LOCATION DE LUXE DFRA
theme: hugo-lithium
ignoreFiles:
  - \.Rmd$ 
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/ 
menu:
  main:
    - name: About
      url: /about/ 
    - name: Instagram
      url: https://www.instagram.com/dfra_location_event?igsh=dmg0cGVtM2F6Zmdq&utm_source=qr
    - name: Snapchat
      url: https://snapchat.com/t/tJ2aFyzU 
    - name: FacebookMarket
      url: https://www.facebook.com/marketplace/item/1750077072428266/?mibextid=6ojiHh
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs 
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
